name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NDK v16.1.4479499
        run: ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;16.1.4479499"
      - name: Build MCinaBox APK with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean :mcinabox:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: mcinabox-debug.apk
          path: mcinabox/build/outputs/apk/debug/mcinabox-debug.apk